### ISSUE TITLE
crash when you hold Spellforger's Codex of wizardry-0.11.3 (https://www.curseforge.com/Minecraft/mc-mods/wizardry-mod)

### ISSUE THREAD

**Issue by ralseilii** [CleanroomMC/LibrarianLib#5] opened 2024-08-24 10:50 UTC
using wizardry-0.11.3 with Forgelin-Continuous and LibrarianLib-Continuous

**Comment by CaliforniaDemise** [comment] 2024-08-24 11:18
Duplicate of #4

**Comment by ChAoSUnItY** [comment] 2024-10-11 13:21
Close due to duplicate.

**Closed as completed by ChAoSUnItY** 2024-10-11 13:21 UTC
Labels: duplicate
